# Generated by Django 5.0.1 on 2024-02-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('orders', models.IntegerField(default=0)),
                ('start_work', models.TimeField()),
                ('end_work', models.TimeField()),
                ('working_time', models.TimeField()),
                ('orders_per_hour', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'DailyWorkReports',
            },
        ),
    ]
