# Generated by Django 5.0.1 on 2024-02-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0008_alter_rating_day_alter_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='hour',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
