# Generated by Django 5.0.1 on 2024-02-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0009_rating_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='hour',
            field=models.TimeField(),
        ),
    ]
