# Generated by Django 5.0.1 on 2024-02-21 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
        ('driver', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardailyreports',
            name='driver',
            field=models.ForeignKey(db_column='driver', on_delete=django.db.models.deletion.CASCADE, to='driver.driver'),
        ),
        migrations.AddField(
            model_name='cardamage',
            name='car',
            field=models.ForeignKey(db_column='car', on_delete=django.db.models.deletion.CASCADE, to='car.car'),
        ),
        migrations.AddField(
            model_name='cardamage',
            name='driver',
            field=models.ForeignKey(db_column='driver', on_delete=django.db.models.deletion.CASCADE, to='driver.driver'),
        ),
    ]
