# Generated by Django 5.0.1 on 2024-02-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyMessages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('posted_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('seen', models.BooleanField(default=False)),
            ],
        ),
    ]
