# Generated by Django 5.0.1 on 2024-02-21 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_initial'),
        ('restaurant', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('driver', models.ForeignKey(db_column='driver', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='driver.driver')),
                ('restaurant', models.ForeignKey(db_column='restaurant', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.restaurant')),
            ],
        ),
    ]
